// 模拟聊天数据
const items = [
	{ title: "How to use Tailwind components?", date: "1 Jan", id: "1" },
	{
		title: "Tailwind Classedddddddddddddddddsddddddddddd fdagfdshfa fdsagfdsg",
		date: "12 Mar",
		id: "2",
		type: "chat",
	},
	{ title: "How to use Tailwind components?", date: "1 Jan", id: "3" },
	{
		title: "explain quantum computing",
		date: "10 Feb",
		isActive: true,
		id: "4",
		type: "audio",
	},
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "5",
		type: "image",
	},
	{ title: "How to create ERP Diagram", date: "22 Jan", id: "6", type: "chat" },
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "7",
		type: "audio",
	},
	{ title: "API Scaling Strategies", date: "1 Jan", id: "8", type: "image" },
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "9",
		type: "chat",
	},
	{ title: "What is GPT UI?", date: "1 Jan", id: "10", type: "audio" },
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "11",
		type: "chat",
	},
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "12",
		type: "chat",
	},
    { title: "How to use Tailwind components?", date: "1 Jan", id: "1" },
	{
		title: "Tailwind Classedddddddddddddddddsddddddddddd fdagfdshfa fdsagfdsg",
		date: "12 Mar",
		id: "2",
		type: "chat",
	},
	{ title: "How to use Tailwind components?", date: "1 Jan", id: "3" },
	{
		title: "explain quantum computing",
		date: "10 Feb",
		isActive: true,
		id: "4",
		type: "audio",
	},
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "5",
		type: "image",
	},
	{ title: "How to create ERP Diagram", date: "22 Jan", id: "6", type: "chat" },
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "7",
		type: "audio",
	},
	{ title: "API Scaling Strategies", date: "1 Jan", id: "8", type: "image" },
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "9",
		type: "chat",
	},
	{ title: "What is GPT UI?", date: "1 Jan", id: "10", type: "audio" },
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "11",
		type: "chat",
	},
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "12",
		type: "chat",
	},
    { title: "How to use Tailwind components?", date: "1 Jan", id: "1" },
	{
		title: "Tailwind Classedddddddddddddddddsddddddddddd fdagfdshfa fdsagfdsg",
		date: "12 Mar",
		id: "2",
		type: "chat",
	},
	{ title: "How to use Tailwind components?", date: "1 Jan", id: "3" },
	{
		title: "explain quantum computing",
		date: "10 Feb",
		isActive: true,
		id: "4",
		type: "audio",
	},
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "5",
		type: "image",
	},
	{ title: "How to create ERP Diagram", date: "22 Jan", id: "6", type: "chat" },
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "7",
		type: "audio",
	},
	{ title: "API Scaling Strategies", date: "1 Jan", id: "8", type: "image" },
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "9",
		type: "chat",
	},
	{ title: "What is GPT UI?", date: "1 Jan", id: "10", type: "audio" },
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "11",
		type: "chat",
	},
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "12",
		type: "chat",
	},
    { title: "How to use Tailwind components?", date: "1 Jan", id: "1" },
	{
		title: "Tailwind Classedddddddddddddddddsddddddddddd fdagfdshfa fdsagfdsg",
		date: "12 Mar",
		id: "2",
		type: "chat",
	},
	{ title: "How to use Tailwind components?", date: "1 Jan", id: "3" },
	{
		title: "explain quantum computing",
		date: "10 Feb",
		isActive: true,
		id: "4",
		type: "audio",
	},
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "5",
		type: "image",
	},
	{ title: "How to create ERP Diagram", date: "22 Jan", id: "6", type: "chat" },
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "7",
		type: "audio",
	},
	{ title: "API Scaling Strategies", date: "1 Jan", id: "8", type: "image" },
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "9",
		type: "chat",
	},
	{ title: "What is GPT UI?", date: "1 Jan", id: "10", type: "audio" },
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "11",
		type: "chat",
	},
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "12",
		type: "chat",
	},
    { title: "How to use Tailwind components?", date: "1 Jan", id: "1" },
	{
		title: "Tailwind Classedddddddddddddddddsddddddddddd fdagfdshfa fdsagfdsg",
		date: "12 Mar",
		id: "2",
		type: "chat",
	},
	{ title: "How to use Tailwind components?", date: "1 Jan", id: "3" },
	{
		title: "explain quantum computing",
		date: "10 Feb",
		isActive: true,
		id: "4",
		type: "audio",
	},
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "5",
		type: "image",
	},
	{ title: "How to create ERP Diagram", date: "22 Jan", id: "6", type: "chat" },
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "7",
		type: "audio",
	},
	{ title: "API Scaling Strategies", date: "1 Jan", id: "8", type: "image" },
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "9",
		type: "chat",
	},
	{ title: "What is GPT UI?", date: "1 Jan", id: "10", type: "audio" },
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "11",
		type: "chat",
	},
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "12",
		type: "chat",
	},
    { title: "How to use Tailwind components?", date: "1 Jan", id: "1" },
	{
		title: "Tailwind Classedddddddddddddddddsddddddddddd fdagfdshfa fdsagfdsg",
		date: "12 Mar",
		id: "2",
		type: "chat",
	},
	{ title: "How to use Tailwind components?", date: "1 Jan", id: "3" },
	{
		title: "explain quantum computing",
		date: "10 Feb",
		isActive: true,
		id: "4",
		type: "audio",
	},
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "5",
		type: "image",
	},
	{ title: "How to create ERP Diagram", date: "22 Jan", id: "6", type: "chat" },
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "7",
		type: "audio",
	},
	{ title: "API Scaling Strategies", date: "1 Jan", id: "8", type: "image" },
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "9",
		type: "chat",
	},
	{ title: "What is GPT UI?", date: "1 Jan", id: "10", type: "audio" },
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "11",
		type: "chat",
	},
	{
		title: "How to use Tailwind components?",
		date: "1 Jan",
		id: "12",
		type: "chat",
	},
];

export default items;